### ISSUE TITLE
dub

### ISSUE THREAD

**Issue by Imperatorn** [redthing1/soop2#1]
Hey, I see you have a list of dub-projects. Are they all on dub?

**Comment by redthing1** [comment]
This is a binary, so it isn't on dub. Do you know of a way to get a binary on dub?

**Comment by Imperatorn** [comment]
I was just thinking in general, I saw you had some other projects :)

A binary on dub could maybe be done through a release.

I think all that's needed is a dub.json, the binary and a release.

But what I meant was, if you have other libraries that you feel would be nice to share, it would be nice to see them in the registry :)

**Comment by redthing1** [comment]
Happy to see you noticed my projects! May I ask how you found me?

Most of my libraries are indeed published on DUB, take a look: https://code.dlang.org/search?q=redthing1

**Comment by Imperatorn** [comment]
I was searching for http libs and browsed here from dub iirc.

But dubs search function is horrible 😅

Maybe you already have a lot of projects there, sorry if I missed them 🙏

**Comment by redthing1** [comment]
Then, may I suggest you check out this project of mine:

https://code.dlang.org/packages/vibrance-z

web server library with a very concise API
